### ISSUE TITLE
data.json 

### ISSUE THREAD

**Issue by ken19980727** [s920128/NAR-BERT-ASR#2]
Hey guy

Can you provide data.json file?

Just want to compare with transformation espnet
Thanks!

**Comment by SiddiqueFarhan** [comment]
Any update about the data.json file, please?

**Comment by ken19980727** [comment]
Did you need whole dataset or just json file?

**Comment by SiddiqueFarhan** [comment]
Actually I was trying to run this project. I believe only the .json file will work there.

**Comment by ken19980727** [comment]
Not exactly.
Also you need the ark file(fbank feature) which convert by
espnet/egs/aishell1

here is a link FYI
https://github.com/espnet/espnet/tree/master/egs/aishell/asr1

Remember just go to stage 2.


Farhan Siddiqui ***@***.***> 於 2022年11月18日 週五 下午5:10寫道：

**Comment by s920128** [comment]
Thanks ken19980727.
You should run ESPnet AISHELL-1 recipe (to stage 2). The recipe will help you to download AISHELL-1 dataset and generate the all file we need (e.g., fbank and data.json).

**Comment by ken19980727** [comment]
This issue will reopen if necessary.
